var _player_index = inst_control_manager.add_player();
my_player = inst_control_manager.get_player(_player_index);
quit_timer = quit_timer_length;
surf_quit_meter = surface_create(32, 32);

reset_all_control_bindings = method(self, function() {
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.UP, 0, vk_up);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.DOWN, 0, vk_down);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.LEFT, 0, vk_left);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.RIGHT, 0, vk_right);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.SHOOT, 0, ord("Z"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.JUMP, 0, ord("X"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.INTERACT, 0, ord("C"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.ITEM, 0, ord("V"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.EXIT, 0, vk_escape);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_UP, 0, vk_up);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_DOWN, 0, vk_down);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_LEFT, 0, vk_left);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_RIGHT, 0, vk_right);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_CONFIRM, 0, vk_enter);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_CANCEL, 0, vk_backspace);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.DELETE_BINDING, 0, vk_delete);

	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.UP, 1, ord("W"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.DOWN, 1, ord("S"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.LEFT, 1, ord("A"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.RIGHT, 1, ord("D"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.SHOOT, 1, ord("L"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.JUMP, 1, vk_semicolon);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.INTERACT, 1, vk_single_quote);
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.ITEM, 1, ord("P"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_UP, 1, ord("W"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_DOWN, 1, ord("S"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_LEFT, 1, ord("A"));
	self.my_player.set_binding(CONTROL_TYPE.KEYBOARD_AND_MOUSE, CONTROL_SOURCE.KEYBOARD, CONTROLS.MENU_RIGHT, 1, ord("D"));

	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.UP, 0,  gp_padu);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.DOWN, 0,  gp_padd);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.LEFT, 0, gp_padl);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.RIGHT, 0, gp_padr);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.SHOOT, 0, gp_face3);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.JUMP, 0, gp_face1);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.INTERACT, 0, gp_face2);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.ITEM, 0, gp_face4);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.EXIT, 0, gp_select);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_UP, 0, gp_padu);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_DOWN, 0, gp_padd);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_LEFT, 0, gp_padl);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_RIGHT, 0, gp_padr);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_CONFIRM, 0, gp_face1);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.MENU_CANCEL, 0, gp_face2);
	self.my_player.set_binding(CONTROL_TYPE.GAMEPAD, CONTROL_SOURCE.GAMEPAD, CONTROLS.DELETE_BINDING, 0, gp_select);
});

self.reset_all_control_bindings();